### ISSUE TITLE
Update github.com/go-jose/go-jose/v3 again

### ISSUE THREAD

**Issue by DrDaveD** [containers/ocicrypt#104]
go-jose version 3.0.3 has a fix for another [security vulnerability](https://github.com/go-jose/go-jose/security/advisories/GHSA-c5q2-7r4c-mv6g), please upgrade.

Is containers/ocicrypt not set up for dependabot?

**Comment by stefanberger** [comment]
> Is containers/ocicrypt not set up for dependabot?

It is but I haven't heared from it. Strange. I just sent a PR.

**Comment by stefanberger** [comment]
Should be fixed now.

**Comment by DrDaveD** [comment]
Thanks. Can we please have a new release?

**Comment by stefanberger** [comment]
> Thanks. Can we please have a new release?

I will make one soon.

**Comment by stefanberger** [comment]
Published v1.1.10 now.
