### ISSUE TITLE
Add PKCS#8 encrypted key support 

### ISSUE THREAD

**Issue by lumjjb** [containers/ocicrypt#48]
Deprecation of PEM encrypted keys (https://go-review.googlesource.com/c/go/+/264159/) doesn't affect the workflow and security model built into the encryption/decryption process. However, it does bring about additional security work for operators that wish to leave their keys on the server password-protected. 

This can be enhanced by supported the newer PKCS#8 encrypted key. However, this is not yet implemented upstreamed, but should be adopted when it is implemented.

**Comment by stefanberger** [comment]
I think this is already supported. There are test cases in imgcrypt that use an encrypted key generated here:

https://github.com/containerd/imgcrypt/blob/bc7d7f2da8e25037a4ec1fc05ec1889e0a77976c/script/tests/test_encryption.sh#L463
