### ISSUE TITLE
Cut v1.4.0 release

### ISSUE THREAD

**Issue by vrothberg** [containers/ocicrypt#62]
Can you cut a new release?  We're about to release a new version of Podman which needs some post-v1.3.0 commits (see https://github.com/containers/podman/pull/14127/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R18).

Cc: @lumjjb

**Comment by lumjjb** [comment]
Done! https://github.com/containers/ocicrypt/releases/tag/v1.1.4

**Comment by vrothberg** [comment]
That was suuuuper quick, thank you so much!
