### ISSUE TITLE
Better Error message for Key Provider execution

### ISSUE THREAD

**Issue by Dsolnik** [containers/ocicrypt#70]
If the Key Provider errors in encryption or decryption, the error message is not very helpful.

On encryption:
```
Unable to finalize encryption: error while retrieving keyprovider protocol command output: Error while running $COMMAND: exit status 1
```

On decryption:
```
decrypting layer sha256:$SHA: missing private key needed for decryption
```

Can we append the stderr to the message here so we can give the user back some information on what happened?

Alternatively, maybe we can add this to the Protocol structs?

**Comment by stefanberger** [comment]
Can you please also provide the commands that you used that lead to the output so we see what you tried?

**Comment by stefanberger** [comment]
@lumjjb Not sure how this will work with existing key providers that wouldn't report this. Not so familiar with the protocol, either.

**Comment by Dsolnik** [comment]
To reproduce this, you can make [simple-ocicrypt-keyprovider](https://github.com/lumjjb/simple-ocicrypt-keyprovider) return a -1 status code.

**Comment by Dsolnik** [comment]
alternatively, maybe we could make this a flag in the key provider config to enable passing through the stderr?

**Comment by stefanberger** [comment]
Did PR #74 resolve your issue. If so, can you close the issue?
