### ISSUE TITLE
RFE: Disable Travis CI on this repo

### ISSUE THREAD

**Issue by cevich** [containers/ocicrypt#81]
**Is your feature request related to a problem? Please describe.**
It doesn't appear Travis-CI is in use on this repo, yet it's explicitly enabled for this repo.

**Describe the solution you'd like**
I'd like to disable Travis-CI to reduce the overall number of containers-org. enabled apps, thereby reducing the maintenance burden.

**Describe alternatives you've considered**
Leave Travis-CI enabled

**Additional context**
Travis-CI has issued multiple security bulletins over the past years.

**Comment by stefanberger** [comment]
I think you can disable it. We used to use it until we moved to github actions.

**Comment by cevich** [comment]
Great, will do.  Thanks for confirmation.
